version: 2.1

description: Delta Brakeman Reports
orbs:
  dscar: naokikimura/dscar@0.1.0
commands:
  execute:
    description: Calculate the difference of Brakeman results between HEAD branch and BASE branch
    parameters:
      starting-points:
        description: Specify the path of starting to search for files to analyze
        type: string
        default: "."
      test-results-path:
        description: Specify the value of the path parameter in the store_test_results step if you need to change it
        type: string
        default: "/tmp/test-results"
    steps:
      - dscar/execute:
          prepare-to-execute:
            - run:
                name: Install Brakeman
                command: sudo gem install brakeman
          analysis-name: Brakeman
          analysis-command: brakeman
          analysis-arguments: -f junit
          calculate-options: |
              --test-case-key=concat(@classname,"#",@name,"=>",normalize-space())
              --namespace=brakeman=https://brakemanscanner.org/
          test-results-path: << parameters.test-results-path >>
jobs:
  execute:
    description: Calculate the difference of Brakeman results between HEAD branch and BASE branch
    parameters:
      starting-points:
        description: Specify the path of starting to search for files to analyze
        type: string
        default: "."
      test-results-path:
        description: Specify the value of the path parameter in the store_test_results step if you need to change it
        type: string
        default: "/tmp/test-results"
    executor:
      name: dscar/default
      docker-image: circleci/ruby
    steps:
      - execute:
          starting-points: << parameters.starting-points >>
          test-results-path: << parameters.test-results-path >>
